/*
Nice List all Tables by Prefix
*/
USE FAMISMod
SELECT TABLE_NAME, COUNT(*)
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME LIKE '%FRSPayHist%'
GROUP BY TABLE_NAME


USE AdventureWorks2014
SELECT TABLE_NAME,COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME LIKE '%Last%'